[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  GOOGLE_REDIRECT_URI = "https://creative-kleicha-a0928a.netlify.app/oauth2callback"
  VITE_GOOGLE_REDIRECT_URI = "https://creative-kleicha-a0928a.netlify.app/oauth2callback"

# Redirect rule for OAuth callback
[[redirects]]
  from = "/oauth2callback"
  to = "/.netlify/functions/google-oauth"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
