[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirect rule for OAuth callback
[[redirects]]
  from = "/oauth2callback"
  to = "/.netlify/functions/google-oauth"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
