[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Environment variables should be set in Netlify UI, not in this file
# This prevents sensitive credentials from being stored in source control
[build.environment]
  # Only non-sensitive values should be here
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "9.x"
  GOOGLE_REDIRECT_URI = "https://creative-kleicha-a0928a.netlify.app/oauth2callback"
  VITE_GOOGLE_REDIRECT_URI = "https://creative-kleicha-a0928a.netlify.app/oauth2callback"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://apis.google.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.googleapis.com https://*.supabase.co; frame-src 'self' https://accounts.google.com;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Redirect rule for OAuth callback
[[redirects]]
  from = "/oauth2callback"
  to = "/.netlify/functions/google-oauth"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
